apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jenana-devops/argocd-env.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://C58A9B695AD37BE5FE8F419FC3F26691.gr7.ap-northeast-2.eks.amazonaws.com
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true    

