apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-extra
spec:
  generators:
    - git:
        repoURL: https://github.com/jenana-devops/argocd-env.git
        revision: HEAD
        files:
          - path: "env/addons/alpha/*.yaml"

  template:
    metadata:
      name: "istio-extra-{{cluster}}"
      #annotations:
        #notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-{{cluster_env}}-addon
      labels:
        app.kubernetes.io/instance: "addons-{{cluster}}"
        krmt.io/cluster: "{{cluster}}"
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: "{{cluster}}"
        namespace: istio-system
      source:
        repoURL: https://charts.helm.sh/incubator
        targetRevision: "0.2.5"
        chart: raw
        helm:
          values: |-
            fullnameOverride: istio-extra

            resources:
              - apiVersion: v1
                kind: Service
                metadata:
                  labels:
                    app: istio-ingressgateway
                    istio: ingressgateway
                  name: istio-ingressgateway-metrics
                spec:
                  ports:
                    - name: http-envoy-prom
                      port: 25090
                      protocol: TCP
                      targetPort: 15090
                  selector:
                    app: istio-ingressgateway
                    istio: ingressgateway
                  type: ClusterIP

              # - apiVersion: cert-manager.io/v1
              #   kind: Certificate
              #   metadata:
              #     name: istio-cert
              #   spec:
              #     commonName: "{{istio.hostname}}"
              #     dnsNames:
              #       - "*.{{istio.hostname}}"
              #     secretName: "istio-cert"
              #     duration: "87600h0m0s"
              #     renewBefore: "70080h0m0s"
              #     issuerRef:
              #       kind: "ClusterIssuer"
              #       name: "cluster-issuer-selfsigned"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
