fullnameOverride: argocd

server:
  replicas: 2

  service:
    type: NodePort
        
  extraArgs:
    - --insecure

  config:
    url: https://ARGOCD_HOSTNAME

    dex.config: |
      connectors:
      - type: github
        id: github
        name: github
        config:
          clientID: $dex.github.clientId
          clientSecret: $dex.github.clientSecret
          teamNameField: slug
          orgs:
            - name: GITHUB_ORG

  rbacConfig:
    policy.default: "role:readonly"
    policy.csv: |
      g, GITHUB_ORG:GITHUB_TEAM, role:admin

  additionalProjects:
    - name: apps
      namespace: argocd
      description: apps project
      sourceRepos:
        - "*"
      destinations:
        - namespace: "*"
          server: "*"
      clusterResourceWhitelist:
        - group: "*"
          kind: "*"

repoServer:
  replicas: 2

configs:
  secret:
    createSecret: true

    #githubSecret: "ARGOCD_WEBHOOK"

    extra:
      #server.secretkey: "ARGOCD_SERVER_SECRET"

      dex.github.clientId: "ARGOCD_GITHUB_ID"
      dex.github.clientSecret: "ARGOCD_GITHUB_SECRET"

    # Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
    # `htpasswd -nbBC 10 "" $PASSWORD | tr -d ':\n' | sed 's/$2y/$2a/'`
    argocdServerAdminPassword: "ARGOCD_PASSWORD"
    # Password modification time defaults to current time if not set
    argocdServerAdminPasswordMtime: "ARGOCD_MTIME"

  # Repositories list to be used by applications
  repositories:
    - name: env-demo
      type: git
      url: https://github.com/jenana-devops/argocd-env.git

