apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: apps
  
  source:
    repoURL: https://github.com/jenana-devops/argocd-env.git
    targetRevision: HEAD
    path: charts/helm-guestbook
  
  destination:
    server: https://kubernetes.default.svc
    # apps namespace 지정이 안되어있을 경우 붙는다. kubectl get all -n my-apps
    namespace: my-apps
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true   

